name: qr_code_attendence_system
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+13

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



#  qr_code_scanner: ^0.3.1  ye krna padha ...   #0.6.1 ye tha
#  qr_flutter: ^1.1.1
#  path_provider: ^0.4.1   ye permanent gone
#  barcode_scan: ^0.0.4
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  modal_progress_hud: ^0.1.3

  google_fonts: ^1.1.0
  data_connection_checker: ^0.3.4
  shared_preferences: ^0.5.10
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2

  image_picker: ^0.6.7+7
  firebase_storage: ^4.0.0
#  basic_utils: ^2.6.2
  file_picker: ^1.4.0+1
#  video_player: ^0.10.2+1
  rflutter_alert: ^1.1.0
  flutter_downloader: ^1.5.0
#  downloads_path_provider: ^0.1.0
#  flushbar: ^1.9.0
#  dio: ^3.0.10

#  commons: ^0.7.8+3
  rich_alert: ^0.1.32

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
     - images/
  fonts:
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
